version: '3'
services:
  nginx:
    image: ${REGISTRY_ADDRESS}/nginx:${IMAGE_TAG}
    restart: always
    depends_on:
      - php-fpm
      - websocket-nodejs
    ports:
      - "443:443"

  php-fpm:
    image: ${REGISTRY_ADDRESS}/php-fpm:${IMAGE_TAG}
    restart: always
    depends_on:
      - mysql
      - redis
      - websocket-nodejs
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      APP_ALLOW: ${APP_ALLOW}
      LOG_CHANNEL: ${LOG_CHANNEL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER}
      CACHE_DRIVER: ${CACHE_DRIVER}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      SESSION_DRIVER: ${SESSION_DRIVER}
      SESSION_LIFETIME: ${SESSION_LIFETIME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_KEY: ${MAILGUN_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_PRIVATE_KEY: ${STRIPE_PRIVATE_KEY}
      CHECKR_APP_KEY: ${CHECKR_APP_KEY}
      CHECKR_BASE_URL: ${CHECKR_BASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_URL: ${AWS_URL}
      AWS_PATH: ${AWS_PATH}
      DISTANCE_MATRIX_API_KEY: ${DISTANCE_MATRIX_API_KEY}
      PLACES_API_KEY: ${PLACES_API_KEY}
      GMAP_API_KEY: ${GMAP_API_KEY}
      DWOLLA_APP_PUBLIC_KEY: ${DWOLLA_APP_PUBLIC_KEY}
      DWOLLA_APP_SECRET_KEY: ${DWOLLA_APP_SECRET_KEY}
      DWOLLA_API_URL: ${DWOLLA_API_URL}
      DWOLLA_APP_FUNDING_SOURCE: ${DWOLLA_APP_FUNDING_SOURCE}
      DEVELOPER_EMAIL: ${DEVELOPER_EMAIL}
      MANAGER_EMAIL: ${MANAGER_EMAIL}
      CEO_EMAIL: ${CEO_EMAIL}
      MANAGER2_EMAIL: ${MANAGER2_EMAIL}
      GOOGLE_RECAPTCHA_KEY: ${GOOGLE_RECAPTCHA_KEY}
      GOOGLE_RECAPTCHA_SECRET: ${GOOGLE_RECAPTCHA_SECRET}
      DL_AI_URL: ${DL_AI_URL}
      DL_AI_KEY: ${DL_AI_KEY}
      MIX_ALLOW_FB_TRACK: ${MIX_ALLOW_FB_TRACK}
      MIX_SOCKET_SERVER_URL: ${MIX_SOCKET_SERVER_URL}
      TWILIO_APP_KEY: ${TWILIO_APP_KEY}
      TWILIO_APP_SECRET: ${TWILIO_APP_SECRET}
      TWILIO_FROM: ${TWILIO_FROM}

  php-cli:
    image: ${REGISTRY_ADDRESS}/php-cli:${IMAGE_TAG}
    depends_on:
      - mysql
      - redis
      - websocket-nodejs
    tty: true
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      APP_ALLOW: ${APP_ALLOW}
      LOG_CHANNEL: ${LOG_CHANNEL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER}
      CACHE_DRIVER: ${CACHE_DRIVER}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      SESSION_DRIVER: ${SESSION_DRIVER}
      SESSION_LIFETIME: ${SESSION_LIFETIME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_KEY: ${MAILGUN_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_PRIVATE_KEY: ${STRIPE_PRIVATE_KEY}
      CHECKR_APP_KEY: ${CHECKR_APP_KEY}
      CHECKR_BASE_URL: ${CHECKR_BASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_URL: ${AWS_URL}
      AWS_PATH: ${AWS_PATH}
      DISTANCE_MATRIX_API_KEY: ${DISTANCE_MATRIX_API_KEY}
      PLACES_API_KEY: ${PLACES_API_KEY}
      GMAP_API_KEY: ${GMAP_API_KEY}
      DWOLLA_APP_PUBLIC_KEY: ${DWOLLA_APP_PUBLIC_KEY}
      DWOLLA_APP_SECRET_KEY: ${DWOLLA_APP_SECRET_KEY}
      DWOLLA_API_URL: ${DWOLLA_API_URL}
      DWOLLA_APP_FUNDING_SOURCE: ${DWOLLA_APP_FUNDING_SOURCE}
      DEVELOPER_EMAIL: ${DEVELOPER_EMAIL}
      MANAGER_EMAIL: ${MANAGER_EMAIL}
      CEO_EMAIL: ${CEO_EMAIL}
      MANAGER2_EMAIL: ${MANAGER2_EMAIL}
      GOOGLE_RECAPTCHA_KEY: ${GOOGLE_RECAPTCHA_KEY}
      GOOGLE_RECAPTCHA_SECRET: ${GOOGLE_RECAPTCHA_SECRET}
      DL_AI_URL: ${DL_AI_URL}
      DL_AI_KEY: ${DL_AI_KEY}
      MIX_ALLOW_FB_TRACK: ${MIX_ALLOW_FB_TRACK}
      MIX_SOCKET_SERVER_URL: ${MIX_SOCKET_SERVER_URL}
      TWILIO_APP_KEY: ${TWILIO_APP_KEY}
      TWILIO_APP_SECRET: ${TWILIO_APP_SECRET}
      TWILIO_FROM: ${TWILIO_FROM}

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

    ports:
      - "33061:3306"

  redis:
    image: redis:5.0-alpine
    restart: always
    volumes:
      - redis:/data
    ports:
      - "63791:6379"

  websocket:
    image: ${REGISTRY_ADDRESS}/websocket:${IMAGE_TAG}
    ports:
      - "8084:8000"
    working_dir: /var/www/websocket
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    tty: true

volumes:
  mysql:
  redis:
